"""
Project Euler -----
Problem Number: 002
-----------------------------------------------------------------------
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

@author: Mario Garcia
"""

import numpy as np
import matefuncs as mf

# Get a list of all Fibonacci numbers up to n = 4 000 000
n = 4000000
a = mf.fiblim(n,enlist=True)

# Select and sum the even numbers of the list
s = 0
for i in range(len(a)):
	if int(np.mod(a[i],2)) is 0:
		s += a[i]

# Print the sum
print s