/**
    Project Euler. Problem 002.
    ---------------------------------------------------------------------
    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will
    be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do
    not exceed four million, find the sum of the even-valued terms.

    @author: Mario Garcia
*/

#include <stdio.h>

// Sum even numbers up to a value equal to 'n'
int sumevens(int n)
{
    int a = 0, b = 1, c = 0, s = 0, i = 1;

    for (i; i<=1000 ; i++ ){
        c = a + b;
        a = b;
        b = c;
        if (c<n){
            if (c%2==0){
                s += c;
            }
        }
        else{
            break;
        }
    }
    return s;
}

// ============= MAIN PROGRAM =============
int main()
{
    int n = 4000000,r;  // Define variables
    r = sumevens(n);    // Sum even Fibonacci numbers

    printf("%d\n",r);  // Display on command Window

    return 0;
}